name: CI

on:
  push:
    branches:
      - "*"
      - "!gh-pages"
  pull_request:
    branches:
      - "*"
      - "!gh-pages"

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      # Install the latest version of swiftformat.
      # Latest compatiable version with our codebase is 0.48.0
      - run: brew update
      - run: brew upgrade swiftformat || brew install swiftformat
      - run: sudo xcode-select -s /Applications/Xcode_12.3.app/Contents/Developer
      - run: make lint
      - run: pod install --project-directory=example
      - run: make build BUILD_SDK='"iphonesimulator14.3"'
      - run: make test TEST_DESTINATION='"platform=iOS Simulator,name=iPhone 11,OS=14.3"'
